tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/command-not-found"
tap "homebrew/core"
cask "osxfuse"
brew "autoconf"
brew "automake"
brew "ctags"
brew "e2fsprogs"
brew "ext4fuse"
brew "ffmpeg"
brew "flex"
brew "git"
brew "gnupg"
brew "libtool"
brew "netcat"
brew "nmap"
brew "zlib", link: true
brew "python"
brew "python@2"
brew "opencv"
brew "pdnsd"
brew "platformio"
brew "pyqt", link: false
brew "shellcheck"
brew "shfmt"
brew "telnet"
brew "thefuck"
brew "valgrind", args: ["HEAD"]
brew "wget"
brew "wine"
brew "youtube-dl"
cask "cheatsheet"
cask "chromedriver"
cask "font-hack-nerd-font"
cask "iterm2"
cask "keycastr"
